sudo: required
services: 
  - docker

before_install: 
  - docker build -t lb0ss/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true lb0ss/docker-react npm run test -- --coverage


deploy: 
  provider: elasticbeanstalk
  region: "us-west-2"
  name: "docker-react"
  env: "Docker-env"
  bucket_name: 
  bucket_path: "docker-react"
  on: 
    branch: main
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY